services:
  msoy-rabbitmq:
    image: rabbitmq:3-management
    container_name: msoy-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: whirled
      RABBITMQ_DEFAULT_PASS: whirledpass
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"

  msoy-db:
    image: postgres:17
    container_name: msoy-db
    restart: always
    environment:
      POSTGRES_DB: msoy
      POSTGRES_USER: msoy
      POSTGRES_PASSWORD: msoy
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    expose:
      - "5432"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data

  msoy-mail:
    image: boky/postfix
    container_name: msoy-mail
    environment:
      HOSTNAME: mail.whirled.social
      POSTFIX_mynetworks: 127.0.0.0/8,172.16.0.0/12
      ALLOW_EMPTY_SENDER_DOMAINS: "true"
      ALLOWED_SENDER_DOMAINS: "whirled.social"
    ports:
      - "25:25"
    volumes:
      - ./data/dkim:/etc/opendkim/keys
    restart: unless-stopped

  msoy-whirled:
    hostname: ${DOCKER_HOSTNAME}
    container_name: msoy-whirled
    build: .
    ports:
      - "9475:8080"
      - "843:843"
      - "4010:4010"
      - "47623:47623"
      - "47624:47624"
      - "47625:47625"
    volumes:
      - ./data/msoy-media:/export/msoy/pages/media/
    depends_on:
      - msoy-rabbitmq
      - msoy-db
      - msoy-mail
    command: ["/start.sh"]

volumes:
  db_data:
  msoy-media:
  dkim: